package org.example

data class AircraftPerformance(
    val ICAO: String,
    val takeOffV2: Int?,
    val takeOffDistance: Int?,
    val takeOffWTC: Char,
    val takeOffRECAT: String,
    val takeOffMTOW: Int,
    val initialClimbIAS: Int?,
    val initialClimbROC: Int?,
    val climb150IAS: Int?,
    val climb150ROC: Int?,
    val climb240IAS: Int?,
    val climb240ROC: Int?,
    val machClimbMACH: Float?,
    val machClimbROC: Int?,
    val cruiseTAS: Int,
    val cruiseMACH: Float?,
    val cruiseCeiling: Int,
    val cruiseRange: Int?,
    val initialDescentMACH: Double?,
    val initialDescentROD: Int?,
    val descentIAS: Int,
    val descentROD: Int?,
    val approachIAS: Int,
    val approachROD: Int?,
    val approachMCS: Int?,
    val landingVat: Int,
    val landingDistance: Int?,
    val landingAPC: String
)